### ISSUE TITLE
Crazy ticks

### ISSUE THREAD

**Issue by jdh30** [fslaborg/FSharp.Charting#36] opened 2014-01-22 11:01 UTC
Axis ranges from 300 to 300000 result in chart ticks with labels like 29999.9999998 that take up half the chart and make it unreadable.

**Comment by dsyme** [comment] 2017-06-07 17:31
Duplicate of https://github.com/fslaborg/FSharp.Charting/issues/63

**Closed by dsyme** 2017-06-07 17:31 UTC
Labels: Up for grabs
